name: Toolset Installation 

# on: 
#  workflow_dispatch

on:
  push:


jobs:
  install_required_tools:
    runs-on: ubuntu-20.04
  
    defaults:
      run:
        working-directory: "./toolset/scripts/"
    steps:
      - uses: actions/checkout@v3

      - name: Toolset Installation 
        run: |
          bash install.sh
      

  baracuda_infra_setup:
    runs-on: ubuntu-20.04
  
    # defaults:
    #   run:
    #     working-directory: "./toolset/scripts/"
      
    env:
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: 
      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}

    steps:
      - uses: actions/checkout@v3

      - name: Toolset Installation 
        run: |
          bash install.sh
      
      - name: Terraform Plan 
        run: |
          bash build.sh -a plan

      - name: List Directories
        run: |
          ls -l 
          ls tf
