name: Toolset Installation 

# on: 
#  workflow_dispatch

on:
  push:


jobs:
  cosmos_data_correction:
    runs-on: ubuntu-20.04
  
    defaults:
      run:
        working-directory: "./toolset/scripts/"
      
    steps:
      - uses: actions/checkout@v3

      - name: Toolset Installation 
        run: |
          bash install.sh