name: Toolset Installation 

# on: 
#  workflow_dispatch

on:
  push:


jobs:
  baracuda_infra_setup:
    runs-on: ubuntu-20.04

    env:
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
  
    # defaults:
    #   run:
    #     working-directory: "./toolset/scripts/"
    steps:
      - uses: actions/checkout@v3

      - name: Toolset Installation 
        run: |
          bash ./toolset/scripts/install.sh

      - name: Terraform Plan 
        run: |
          az login --service-principal -u ${{ env.ARM_CLIENT_ID }} -p ${{ env.ARM_CLIENT_SECRET }} --tenant ${{ env.ARM_TENANT_ID }}

          bash ./build.sh -a plan

      - name: List Directories
        run: |
          ls -l 
          ls -a tf
          az version
          
